### ISSUE TITLE
Terraform 0.12 support

### ISSUE THREAD

**Issue by Mor-Walkme** [terraform-providers/terraform-provider-postgresql#79]
### Terraform Version
Terraform v0.12.0-beta2

### Affected Resource(s)
All postgres resources, i tested "postgresql_role" and "postgresql_database"

### Terraform Configuration Files
```hcl
# RDS Operational provider
provider "postgresql" {
  alias           = "operational"
  host            = "somehost"
  port            = 5432
  database        = "somedatabase"
  username        = "someusername"
  password        = "somepassword"
  sslmode         = "disable"
  connect_timeout = 15
  superuser       = false
}

resource "postgresql_role" "rds_operational_user" {
  provider            = "postgresql.operational"
  name                = "appusername"
  login               = true
  password            = "apppassword"
  skip_reassign_owned = true
}
```

### Debug Output
```
panic: can't convert 0x4 to cty.Value
2019-05-13T10:20:45.895+0300 [TRACE] plugin.terraform-provider-postgresql: 
2019-05-13T10:20:45.895+0300 [DEBUG] plugin.terraform-provider-postgresql: goroutine 34 [running]:
2019-05-13T10:20:45.895+0300 [DEBUG] plugin.terraform-provider-postgresql: github.com/hashicorp/terraform/config/hcl2shim.HCL2ValueFromConfigValue(0xdfd240, 0x1186210, 0x1186210, 0x0, 0x0, 0xc0002c495f)
2019-05-13T10:20:45.895+0300 [DEBUG] plugin.terraform-provider-postgresql: 	/home/mor.h/go/pkg/mod/github.com/hashicorp/terraform@v0.12.0-rc1/config/hcl2shim/values.go:229 +0x86d
2019-05-13T10:20:45.895+0300 [DEBUG] plugin.terraform-provider-postgresql: github.com/hashicorp/terraform/helper/plugin.(*GRPCProviderServer).PrepareProviderConfig.func1(0xc0002de5a0, 0x1, 0x1, 0x11c24c0, 0xc0002c495e, 0x0, 0x0, 0x11c24c0, 0xc0002c495f, 0xdfd080, ...)
2019-05-13T10:20:45.895+0300 [DEBUG] plugin.terraform-provider-postgresql: 	/home/mor.h/go/pkg/mod/github.com/hashicorp/terraform@v0.12.0-rc1/helper/plugin/grpc_provider.go:163 +0x17e
2019-05-13T10:20:45.895+0300 [DEBUG] plugin.terraform-provider-postgresql: github.com/zclconf/go-cty/cty.transform(0xc0002de5a0, 0x1, 0x1, 0x11c24c0, 0xc0002c495e, 0x0, 0x0, 0xc00000f3c0, 0x0, 0x0, ...)
2019-05-13T10:20:45.895+0300 [DEBUG] plugin.terraform-provider-postgresql: 	/home/mor.h/go/pkg/mod/github.com/zclconf/go-cty@v0.0.0-20190430221426-d36a6f0dbffd/cty/walk.go:181 +0xc2
2019-05-13T10:20:45.895+0300 [DEBUG] plugin.terraform-provider-postgresql: github.com/zclconf/go-cty/cty.transform(0x0, 0x0, 0x0, 0x11c25c0, 0xc000134038, 0xe46c80, 0xc00012ce40, 0xc00000f3c0, 0xc00012ce40, 0x0, ...)
2019-05-13T10:20:45.895+0300 [DEBUG] plugin.terraform-provider-postgresql: 	/home/mor.h/go/pkg/mod/github.com/zclconf/go-cty@v0.0.0-20190430221426-d36a6f0dbffd/cty/walk.go:168 +0xa1c
2019-05-13T10:20:45.895+0300 [DEBUG] plugin.terraform-provider-postgresql: github.com/zclconf/go-cty/cty.Transform(...)
2019-05-13T10:20:45.895+0300 [DEBUG] plugin.terraform-provider-postgresql: 	/home/mor.h/go/pkg/mod/github.com/zclconf/go-cty@v0.0.0-20190430221426-d36a6f0dbffd/cty/walk.go:89
2019-05-13T10:20:45.895+0300 [DEBUG] plugin.terraform-provider-postgresql: github.com/hashicorp/terraform/helper/plugin.(*GRPCProviderServer).PrepareProviderConfig(0xc000010908, 0x11c1580, 0xc00012c4e0, 0xc00012c510, 0xc000010908, 0xc00012c4e0, 0xc000075bd0)
2019-05-13T10:20:45.895+0300 [DEBUG] plugin.terraform-provider-postgresql: 	/home/mor.h/go/pkg/mod/github.com/hashicorp/terraform@v0.12.0-rc1/helper/plugin/grpc_provider.go:121 +0x257
2019-05-13T10:20:45.895+0300 [DEBUG] plugin.terraform-provider-postgresql: github.com/hashicorp/terraform/internal/tfplugin5._Provider_PrepareProviderConfig_Handler(0xf50c20, 0xc000010908, 0x11c1580, 0xc00012c4e0, 0xc0000a87d0, 0x0, 0x11c1580, 0xc00012c4e0, 0xc000267ef0, 0xa7)
2019-05-13T10:20:45.895+0300 [DEBUG] plugin.terraform-provider-postgresql: 	/home/mor.h/go/pkg/mod/github.com/hashicorp/terraform@v0.12.0-rc1/internal/tfplugin5/tfplugin5.pb.go:2893 +0x23e
2019-05-13T10:20:45.895+0300 [DEBUG] plugin.terraform-provider-postgresql: google.golang.org/grpc.(*Server).processUnaryRPC(0xc000478480, 0x11cca60, 0xc000478f00, 0xc000524000, 0xc00020c9c0, 0x191ccb8, 0x0, 0x0, 0x0)
2019-05-13T10:20:45.895+0300 [DEBUG] plugin.terraform-provider-postgresql: 	/home/mor.h/go/pkg/mod/google.golang.org/grpc@v1.18.0/server.go:966 +0x470
2019-05-13T10:20:45.895+0300 [DEBUG] plugin.terraform-provider-postgresql: google.golang.org/grpc.(*Server).handleStream(0xc000478480, 0x11cca60, 0xc000478f00, 0xc000524000, 0x0)
2019-05-13T10:20:45.895+0300 [DEBUG] plugin.terraform-provider-postgresql: 	/home/mor.h/go/pkg/mod/google.golang.org/grpc@v1.18.0/server.go:1245 +0xd25
2019-05-13T10:20:45.895+0300 [DEBUG] plugin.terraform-provider-postgresql: google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc000036480, 0xc000478480, 0x11cca60, 0xc000478f00, 0xc000524000)
2019-05-13T10:20:45.895+0300 [DEBUG] plugin.terraform-provider-postgresql: 	/home/mor.h/go/pkg/mod/google.golang.org/grpc@v1.18.0/server.go:685 +0x9f
2019-05-13T10:20:45.895+0300 [DEBUG] plugin.terraform-provider-postgresql: created by google.golang.org/grpc.(*Server).serveStreams.func1
2019-05-13T10:20:45.895+0300 [DEBUG] plugin.terraform-provider-postgresql: 	/home/mor.h/go/pkg/mod/google.golang.org/grpc@v1.18.0/server.go:683 +0xa1
2019-05-13T10:20:45.897+0300 [DEBUG] plugin: plugin process exited: path=/home/mor.h/.terraform.d/plugins/linux_amd64/terraform-provider-postgresql pid=19436 error="exit status 2"
2019/05/13 10:20:45 [WARN] <root>: eval: *terraform.EvalValidateProvider, non-fatal err: rpc error: code = Unavailable desc = transport is closing
2019/05/13 10:20:45 [ERROR] <root>: eval: *terraform.EvalSequence, err: rpc error: code = Unavailable desc = transport is closing
2019/05/13 10:20:45 [ERROR] <root>: eval: *terraform.EvalOpFilter, err: rpc error: code = Unavailable desc = transport is closing
2019/05/13 10:20:45 [ERROR] <root>: eval: *terraform.EvalSequence, err: rpc error: code = Unavailable desc = transport is closing
2019/05/13 10:20:45 [TRACE] [walkValidate] Exiting eval tree: provider.postgresql.operational
2019/05/13 10:20:45 [TRACE] vertex "provider.postgresql.operational": visit complete
2019/05/13 10:20:45 [TRACE] dag/walk: upstream of "postgresql_role.rds_operational_user" errored, so skipping
2019/05/13 10:20:45 [TRACE] dag/walk: upstream of "provider.postgresql.operational (close)" errored, so skipping
2019/05/13 10:20:45 [TRACE] dag/walk: upstream of "meta.count-boundary (EachMode fixup)" errored, so skipping
2019/05/13 10:20:45 [TRACE] dag/walk: upstream of "root" errored, so skipping
2019-05-13T10:20:45.897+0300 [DEBUG] plugin: plugin exited
```
### Panic Output
https://gist.github.com/Mor-Walkme/8ba6549d49cc96baaf92d32c3df1bff1

### Steps to Reproduce
terraform apply

**Comment by mavogel** [comment]
@Mor-Walkme the provider is not `v0.12` ready yet. More internal updates have to be made for this. We will keep this issue linked to the PR

**Comment by mlehner616** [comment]
What's the roadmap for this to be 0.12 ready? Now that 0.12 is released, is it expected that this will be ready soon or is this blocked by something required in 0.12.1+?

**Comment by mavogel** [comment]
@cyrilgdn do we have any ETA yet for supporting v0.12?

**Comment by nunofernandes** [comment]
Running terraform 0.12checklist gets me to:

```
- [ ] Upgrade provider "postgresql" to a version that is compatible with Terraform 0.12.
  
  No compatible version is available for automatic installation at this time. If this provider is still supported (not archived) then a compatible release should be available soon. For more information, check for 0.12 compatibility tasks in the provider's issue tracker.
```

**Comment by cyrilgdn** [comment]
Hi all, sorry I'm a bit late on this as I was part in vacations and part busy these last weeks. I'll take a look at this upgrade this week and will ask for a new release for that as soon as it's merged. (I just need to read again the Terraform documentation about upgrading to 0.12 to be sure I understood correctly what it means for providers)

**Comment by cyrilgdn** [comment]
Hi all, as I said in PR #83 , I'll take a look on this upgrade this week and will create a new release as soon as it's merged. (sorry for the late answer)

**Comment by cyrilgdn** [comment]
PR #87 (which replace #83) has been merged. You can follow the GitHub repository to be alerted when the v1.0.0 will be released (normally in the next hours)

**Comment by cyrilgdn** [comment]
Version 1.0.0 with the Terraform v0.12 compatibility  has been [released](https://github.com/terraform-providers/terraform-provider-postgresql/releases/tag/v1.0.0)
